### ISSUE TITLE
Prototype exception conditions are ambiguous: must one, or all three, be met?

### ISSUE THREAD

**Issue by chris-morgan** [kemitchell/api-copyleft-license#39]
> You need not contribute prototype changes, extensions, or applications that you do not end up using for more than fourteen calendar days, share with anyone else, or use to provide a service to anyone else.

I believe this is supposed to allow things that meet any one of these three conditions to be excepted, but as worded it’s ambiguous: it can readily be interpreted as only excepting things that meet *all three* conditions. Under *that* interpretation, internal tooling would only be excepted for two weeks.

I believe that the change in #25 (which changed “sharing” to “share”, and “providing” to “provide”) made this less clear, and did not benefit anything. Adjusting the wording further might be a good idea, but I would also consider simply reverting #25 to be reasonable solution.

**Comment by kemitchell** [comment]
Which of the "or"s are you worried might be read as "and"? Both?

**Comment by kemitchell** [comment]
This is resolved in #40.
