### ISSUE TITLE
Consider renaming this license?

### ISSUE THREAD

**Issue by simerplaha** [kemitchell/api-copyleft-license#45]
Although there is no formal definition for this but the term "copyleft" can sometimes get referred to as being a "viral" or "infectious" license. From what I understand this license is not viral, it only encourages sharing.

I think the old name "Shared component license" was a good name for this license or may be a new name if possible?

**Comment by kemitchell** [comment]
I've put out [a call on my blog](https://writing.kemitchell.com/2020/01/13/Renaming-API-Copyleft.html), as well.

**Comment by kemitchell** [comment]
@simerplaha still thinking about a new name for this license, especially since I've just worked through all outstanding PRs, and done another review-revise pass.

Still looking for a good, evocative name.

"Singleton" is probably the best so far. It gets us that connotation of there being one instance, and everyone tending to that one instance, rather than duplicating effort.

I feel like there's probably a good name out there on the theme of drawing in others. Unfortunately, most of the prospects I've found along that line---Whirlpool, Vortex, Cyclone---tend to have negative, involuntary connotations.

I'm trying to do more brainstorming around the idea of joint or collective effort. "Rowing Together" than being sucked in.

**Comment by daisylb** [comment]
> I'm trying to do more brainstorming around the idea of joint or collective effort.

I like the word "collective" itself! "Collective License" has a good ring to it; "Collective Code License" also has some nice alliteration going on.

**Comment by kemitchell** [comment]
@excitedleigh hmm, that's quite a thought! Thank you!

**Comment by BTBurke** [comment]
I like Leigh's idea for Collective Code License, but to me "collective" implies joint ownership and muddies the waters.  How about "Collaborative Code License"?

**Comment by kemitchell** [comment]
Gee. We're really heading back to "Shared Component License", aren't we?

**Comment by kemitchell** [comment]
"Shared Resource License"?

**Comment by daisylb** [comment]
My two cents on "Shared Component License" and "Shared Resource License" is that they wouldn't jump out much in a long list of licenses, which does the text of the license itself injustice. IMO an ideal name would be one that some one scanning through such a list, or looking at package metadata of something that uses it, is going to see and think "that's new and interesting and I'd like to learn more".

"Collaborative Code License" is my personal favourite of all of the suggestions so far. It feels modern and approachable and simple, which fits well with the license text.

Another consideration is how it'll get abbreviated. I'm not sure how SPDX identifiers get picked, but if a third party picks it they'd probably abbreviate "Collaborative Code License" as "CCL-2.0", but "Collaborative License" as "Collab-2.0" which feels nicer and more attention-grabbing to me at least.

On the other hand, I do like the "Code"; it's more informal than, say, "Software" so it more effectively communicates that it was drafted anew in the last decade, and distinguishes it from the lengthy, intimidating tomes of old.

With all of that said, this is of course all very subjective, and the vibe someone else gets when they hear any of these names could be totally different to mine!

**Comment by BTBurke** [comment]
The word "share" doesn't have a good connotation in a software licensing context, but maybe that's just me.  I immediately think of "shareware" and "share-alike".  I'm no expert here, but aren't share-alike licenses a category of "viral" licenses?  That might undermine the goal of setting this apart from licenses like GPL.

**Comment by kemitchell** [comment]
I do share a feeling that the fuzzy "commons" vocabulary of days of yore sounds fairly well sucked dry. "Collaborate". "Share". "Common". "Open". "Free". Meh.

I have had some success with snappier names on a theme, like [Parity](https://pariylicense.com) and [Prosperity](https://prosperitylicense.com).

I'll keep thinking.

Naming this is hard. Until you come up with the name. Then it's obvious in hindsight.

**Comment by kemitchell** [comment]
How about?:
- Potluck License
- Pastoral Software License

**Comment by BTBurke** [comment]
Some other ideas:

* Reciprocity
* Mutuality

Or in latin?

* Consocio (associate, be in league with, hold in common, share, unite in making)

**Comment by kemitchell** [comment]
A friend came up with a fun, quirky name: Round Robin!

There are some technical usages, but it's also used in sport, and features quite interestingly in history. I particularly enjoyed these:

https://en.wikipedia.org/wiki/Round-robin_(document)

https://en.wikipedia.org/wiki/Round-robin_letter
