### ISSUE TITLE
[Question] Are definitions required?

### ISSUE THREAD

**Issue by simerplaha** [kemitchell/api-copyleft-license#46]
Definitions of terms like "the Software", "License", "You", "modify" (this license uses "change") etc are found in many other licenses like Apache2, MPL, GPLs etc. Although their meanings are obvious I guess there is a reason they have them within the license.

Are they required here?

**Comment by kemitchell** [comment]
@simerplaha I see you opened then closed this.

Overall, there's no magic to definitions in legal terms. If defining terms helps to make the terms clearer or more workable, for relatively little cost in readability, that's often worthwhile. In API Copyleft, I think we can get away without them, relying instead on definitions and context hints in the operative sections themselves.

**Comment by simerplaha** [comment]
Hey Kyle, thought I was over thinking a bit too much so I closed it :|

That make sense. Thank you :)
